import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { extname, join, resolve } from 'node:path';

/**
 * `test-design-epic-platform-4.md` E4-AV01 (4.1 AC "no functional-role or
 * root special case"; 4.2-1 "no FR branch in the identity-card decision") AND
 * E4-C02's own audit half ("no executable `S<n>` identifier remains in
 * `src/` or `test/`", 4.1-2, 4.1-4) — both Planned. `s42d-ds-05`
 * (`s42d-ds-dev-seed-spine.e2e-spec.ts`) already proves the E4-AV01 DB-level
 * facts (the file is gone, the npm alias fails, `create:root` runs the
 * repointed chain). What is still Planned for E4-AV01 is the plan's own
 * STATIC oracle: `git grep -n
 * "dev-grant-root|canEditS1|isAllowedForTarget|EDIT_USER_FEATURE|
 * user-management:edit" -- src scripts package.json`, where only dated /
 * historical comments are permitted. E4-C02's own static half is the sibling
 * oracle over the retired `S<n>` matrix-row identifiers. This spec automates
 * both greps so a rerun does not depend on a human re-typing them.
 *
 * Scenario docs:
 *   docs/test-cases/access-control-kernel/fr-bootstrap/
 *     e4-av01-legacy-gate-absence-in-production-source.md
 *
 * Static, DB-free, Nest-free — pure `node:fs` reads, same shape as
 * `dev-seed-absence.spec.ts` in this same directory (E4-C06 obligation (6)).
 * Runs under `npm test` (the unit project), not `npm run test:e2e`.
 *
 * ── SCOPE, STATED RATHER THAN HIDDEN ─────────────────────────────────────
 * The plan's own grep target for E4-AV01 is `src scripts package.json` —
 * production source, not test evidence. This spec walks every `.ts` file
 * under `src/` and `scripts/`, EXCLUDING `__tests__/` directories and
 * `*.spec.ts` files, plus `package.json` itself, for BOTH the five
 * root/FR-special-case identifiers and the retired `S<n>` pattern. Unit and
 * e2e specs are deliberately out of this file's scope: several of them
 * contain these same strings ON PURPOSE, as NEGATIVE evidence that the
 * special case is gone —
 * `access-control-facade.adapter.spec.ts` asserts
 * `expect(isAllowed).not.toHaveBeenCalledWith(VIEWER, 'user-management:edit')`
 * and has a `describe` block titled "the retired `'S1'` identifier is just
 * an unmatched string"; `acm5-section-access.e2e-spec.ts` (`ACM5-SA-06`) uses
 * the retired `'S1'` string as its unsupported-section example, asserting it
 * resolves `'none'`; `write-adoption.e2e-spec.ts` names `canEditS1` and the
 * dead `user-management:edit` OR clause in history comments. A text-only
 * grep cannot tell "the branch exists" from "a test proves the branch does
 * not exist," so those files are read and recorded by hand in the E4-AV01
 * scenario doc above rather than swept by this mechanical check. Scoping to
 * production source is where a mechanical oracle is sound: a match there is
 * never a negative-test artifact, because behavioural negatives belong in
 * `test/`, not in `src/`/`scripts/`. (Verified 2026-09-13: every `S<n>` hit
 * remaining in production `src/` — `PLAT-E4-S4.1a`/`S4.1b`/`S4.1c`/`S4.2c`
 * epic/story tags and `§3.2 row S1/S4/S9/S10/S11/S16` matrix-row citations —
 * is a comment line; none survives Test 5 below.)
 */

const BACKEND_ROOT = resolve(__dirname, '../../../../');
const ROOTS = ['src', 'scripts'] as const;
const PACKAGE_JSON = resolve(BACKEND_ROOT, 'package.json');

// The plan's own five identifiers, verbatim.
const PATTERNS: Array<{ name: string; pattern: RegExp }> = [
  { name: 'dev-grant-root', pattern: /dev-grant-root/ },
  { name: 'canEditS1', pattern: /canEditS1/ },
  { name: 'isAllowedForTarget', pattern: /isAllowedForTarget/ },
  { name: 'EDIT_USER_FEATURE', pattern: /EDIT_USER_FEATURE/ },
  { name: 'READ_USER_FEATURE', pattern: /READ_USER_FEATURE/ },
  { name: 'user-management:edit', pattern: /user-management:edit/ },
];

interface Hit {
  file: string;
  line: number;
  text: string;
  pattern: string;
}

/** Every `.ts` file under `dir`, skipping `__tests__/` and `*.spec.ts`. */
function collectProductionSources(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    // `generated/` is the gitignored Prisma client output (regenerated by
    // postinstall, per CLAUDE.md) — it embeds the whole `schema.prisma` text,
    // comments included, as a string literal, and is not hand-authored
    // production source this obligation is about.
    if (
      entry === '__tests__' ||
      entry === 'node_modules' ||
      entry === 'generated'
    )
      continue;
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      out.push(...collectProductionSources(full));
    } else if (extname(entry) === '.ts' && !entry.endsWith('.spec.ts')) {
      out.push(full);
    }
  }
  return out;
}

/** A line whose first non-whitespace characters open or continue a comment. */
function isCommentLine(line: string): boolean {
  const trimmed = line.trimStart();
  return (
    trimmed.startsWith('//') ||
    trimmed.startsWith('/*') ||
    trimmed.startsWith('*')
  );
}

function scanFile(file: string): Hit[] {
  const hits: Hit[] = [];
  const lines = readFileSync(file, 'utf8').split('\n');
  lines.forEach((text, index) => {
    if (isCommentLine(text)) return; // historical commentary is permitted
    for (const { name, pattern } of PATTERNS) {
      if (pattern.test(text)) {
        hits.push({ file, line: index + 1, text: text.trim(), pattern: name });
      }
    }
  });
  return hits;
}

function allProductionSources(): string[] {
  const files: string[] = [];
  for (const root of ROOTS) {
    const dir = resolve(BACKEND_ROOT, root);
    if (existsSync(dir)) files.push(...collectProductionSources(dir));
  }
  return files;
}

describe('E4-AV01 · no legacy root/FR special-case identifier remains executable in production source', () => {
  it('none of the five retired identifiers appears outside a comment, anywhere under src/ or scripts/ (excluding __tests__/*.spec.ts)', () => {
    const hits = allProductionSources().flatMap(scanFile);
    if (hits.length > 0) {
      const report = hits
        .map((h) => `${h.file}:${h.line} [${h.pattern}] ${h.text}`)
        .join('\n');
      throw new Error(
        `Found ${hits.length} executable reference(s) to a retired root/FR ` +
          `special-case identifier (E4-AV01):\n${report}`,
      );
    }
    expect(hits).toEqual([]);
  });

  it('none of the five retired identifiers appears outside a comment in package.json', () => {
    const source = readFileSync(PACKAGE_JSON, 'utf8');
    // package.json has no comment syntax — any match at all is executable
    // (an npm script value, a dependency name, etc).
    for (const { name, pattern } of PATTERNS) {
      expect(pattern.test(source)).toBe(false);
      void name;
    }
  });

  it('scripts/dev-grant-root.ts no longer exists on disk (mirrors s42d-ds-05 Test 1; DB-free)', () => {
    expect(existsSync(resolve(BACKEND_ROOT, 'scripts/dev-grant-root.ts'))).toBe(
      false,
    );
  });

  it('package.json′s create:root is the repointed chain, and db:dev:grant-root does not alias a still-existing script', () => {
    const pkg = JSON.parse(readFileSync(PACKAGE_JSON, 'utf8')) as {
      scripts?: Record<string, string>;
    };
    const scripts = pkg.scripts ?? {};
    expect(scripts['create:root']).toBe(
      'npm run db:seed && npm run db:bootstrap:access-control',
    );
    if (scripts['db:dev:grant-root']) {
      // If the alias still exists at all, it must not reference a script that
      // is actually present on disk — s42d-ds-05 Test 2 already proves the
      // live behaviour (npm's own "Missing script" failure); this is the
      // static half of the same fact.
      expect(
        existsSync(resolve(BACKEND_ROOT, 'scripts/dev-grant-root.ts')),
      ).toBe(false);
    }
  });

  it('sanity: the resolver actually walks real production files (a false negative here would silently pass every check above for the wrong reason)', () => {
    const files = allProductionSources();
    expect(files.length).toBeGreaterThan(50);
    expect(files.some((f) => f.endsWith('section-access-matrix.ts'))).toBe(
      true,
    );
    expect(files.some((f) => f.endsWith('.spec.ts'))).toBe(false);
    expect(files.some((f) => f.includes('__tests__'))).toBe(false);
  });
});

// A bare `S<n>` token, word-bounded so it never matches inside a longer
// identifier (`US10`, `IOS1`) — but DOES match an epic/story tag like
// `S4.1a` or a `§3.2 row S9` citation, which is exactly why this check is
// scoped to comment-exempt production source: every real hit found at
// 2026-09-13 is one of those two comment shapes, never a live branch.
const RETIRED_SECTION_ID_PATTERN = /\bS[0-9]{1,2}\b/;

describe('E4-C02 · no executable retired S<n> section identifier remains in production source', () => {
  it('no S<n> token appears outside a comment, anywhere under src/ or scripts/ (excluding __tests__/*.spec.ts)', () => {
    const hits: Array<{ file: string; line: number; text: string }> = [];
    for (const file of allProductionSources()) {
      const lines = readFileSync(file, 'utf8').split('\n');
      lines.forEach((text, index) => {
        if (isCommentLine(text)) return;
        if (RETIRED_SECTION_ID_PATTERN.test(text)) {
          hits.push({ file, line: index + 1, text: text.trim() });
        }
      });
    }
    if (hits.length > 0) {
      const report = hits
        .map((h) => `${h.file}:${h.line} ${h.text}`)
        .join('\n');
      throw new Error(
        `Found ${hits.length} executable reference(s) to a retired S<n> ` +
          `section identifier (E4-C02):\n${report}`,
      );
    }
    expect(hits).toEqual([]);
  });

  it('SECTION_ACCESS_MATRIX declares only human-readable "profile:*" keys, no S<n> row', () => {
    const matrixFile = allProductionSources().find((f) =>
      f.endsWith('section-access-matrix.ts'),
    );
    expect(matrixFile).toBeDefined();
    const source = readFileSync(matrixFile!, 'utf8');
    // Every quoted object-key line, ignoring comments.
    const keyLines = source
      .split('\n')
      .filter((line) => !isCommentLine(line))
      .filter((line) => /^\s*['"][a-z][a-z0-9:_-]*['"]\s*:/i.test(line.trim()));
    expect(keyLines.length).toBeGreaterThan(0);
    for (const line of keyLines) {
      expect(line).not.toMatch(RETIRED_SECTION_ID_PATTERN);
      expect(line.trim()).toMatch(/^['"][a-z]+:[a-z-]+['"]/);
    }
  });
});
